#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import agent
import os

vpn_port = os.environ['TCP_PORTS_RANGE'].split('-')[0]
controller_version = os.environ.get('IMAGE_URL', '').split(':')[-1]

config = agent.read_envfile('config.env')
bits = sum(bin(int(x)).count('1') for x in config.get('OVPN_NETWORK', '').split('.'))
vpn_network = f"{config.get('OVPN_NETWORK', '')}/{bits}"
metrics_retension_days = config.get('RETENTION_DAYS', '30')

loki = agent.read_envfile('loki.env')
logs_retention_days = loki.get('LOKI_RETENTION', '180d')

info = {
    'vpn_port': vpn_port,
    'vpn_network': vpn_network,
    'controller_version': controller_version,
    'metrics_retention_days': int(metrics_retension_days),
    'logs_retention_days': int(logs_retention_days.rstrip('d')),
}

with open('platform.env', 'w') as env:
    env.write(f'PLATFORM_INFO={json.dumps(info)}\n')

