server:
  disable: true

clients:
  - url: http://${LOKI_ADDR}:${LOKI_HTTP_PORT}/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: syslog
    syslog:
      listen_address: ${PROMTAIL_ADDRESS}:${PROMTAIL_PORT}
      labels:
        job: "syslog"
        controller_name: ${OVPN_CN}
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'
