{
 "title": "Operating system",
 "description": "Netdata dashboards for Grafana via Prometheus.",
 "tags": [
  "netdata",
  "prometheus",
  "unit",
  "nethsecurity"
 ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   { "name": "unit", "label": "Firewall unit", "query": { "query": "label_values(unit)" } },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "vpninterface",
    "label": "VPN interface",
    "query": {
     "query": "label_values(net_bytes_recv{unit=~\"$unit\",interface=~\"tun.*|tap.*|ipsec.*|wg.*\"},interface)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System overview: load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System load average",
   "type": "timeseries",
   "description": "Current system load, i.e. the number of processes using CPU or waiting for system resources (usually CPU and disk). The 3 metrics refer to 1, 5 and 15 minute averages. The system calculates this once every 5 seconds.\n\nFor more information check this [Wikipedia article](https://en.wikipedia.org/wiki/Load_(computing))",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_load1{unit=~\"$unit\"}",
     "legendFormat": "load1"
    },
    {
     "expr": "system_load5{unit=~\"$unit\"}",
     "legendFormat": "load5"
    },
    {
     "expr": "system_load15{unit=~\"$unit\"}",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "System overview: CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total CPU utilization",
   "type": "timeseries",
   "description": "Total CPU utilization (all cores). 100% here means there is no CPU idle time at all. You can get per core usage at the _CPUs_ section and per application usage at the _Applications monitoring_ section.\n\nKeep an eye on **iowait**. If it is constantly high, your disks are a bottleneck and they slow your system down.\n\nAn important metric worth monitoring, is **softirq**. A constantly high percentage of softirq may indicate network driver issues.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{cpu=\"cpu-total\",unit=~\"$unit\"}",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "System overview: network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "IPv4 bandwidth",
     "type": "timeseries",
     "description": "Total IPv4 Traffic.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "rate(nstat_IpExtInOctets{unit=~\"$unit\",name=\"netstat\"}[2m])*8/1000 + rate(nstat_IpExtOutOctets{unit=~\"$unit\",name=\"netstat\"}[2m])*8/1000",
       "legendFormat": "Kbits/s"
      }
     ]
    },
    {
     "title": "IPv6 bandwidth",
     "type": "timeseries",
     "description": "Total IPv6 Traffic.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "rate(nstat_Ip6InOctets{unit=~\"$unit\",name=\"snmp6\"}[2m])*8/1000 + rate(nstat_Ip6OutOctets{unit=~\"$unit\",name=\"snmp6\"}[2m])*8/1000",
       "legendFormat": "Kbits/s"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: RAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "System RAM",
     "type": "timeseries",
     "description": "System Random Access Memory (i.e. physical memory) usage.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "mem_used{unit=~\"$unit\"}/1048576",
       "legendFormat": "used"
      },
      {
       "expr": "mem_buffered{unit=~\"$unit\"}/1048576",
       "legendFormat": "buffered"
      },
      {
       "expr": "mem_cached{unit=~\"$unit\"}/1048576",
       "legendFormat": "cached"
      },
      {
       "expr": "mem_free{unit=~\"$unit\"}/1048576",
       "legendFormat": "free"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: network interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "net",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Bandwidth IN",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "targets": [
      {
       "expr": "sum(rate(net_bytes_recv{unit=~\"$unit\"}[2m]))*8/1000",
       "legendFormat": "recv"
      }
     ]
    },
    {
     "title": "Bandwidth OUT",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "targets": [
      {
       "expr": "sum(rate(net_bytes_sent{unit=~\"$unit\"}[2m]))*8/1000",
       "legendFormat": "sent"
      }
     ]
    },
    {
     "title": "Packets IN",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "targets": [
      {
       "expr": "sum(rate(net_packets_recv{unit=~\"$unit\"}[2m]))",
       "legendFormat": "packets/s"
      }
     ]
    },
    {
     "title": "Packets OUT",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "targets": [
      {
       "expr": "sum(rate(net_packets_sent{unit=~\"$unit\"}[2m]))",
       "legendFormat": "packets/s"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk I/O",
     "type": "timeseries",
     "description": "Total Disk I/O, for all physical disks. You can get detailed information about each disk at the _Disks_ section and per application Disk usage at the _Applications Monitoring_ section.\n\nPhysical are all the disks that are listed in `/sys/block`, but do not exist in `/sys/devices/virtual/block`.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "sum(rate(diskio_read_bytes{unit=~\"$unit\"}[2m]))/1024 + sum(rate(diskio_write_bytes{unit=~\"$unit\"}[2m]))/1024",
       "legendFormat": "KiB/s"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "System processes",
     "type": "timeseries",
     "description": "System processes. **Running** are the processes in the CPU. **Blocked** are processes that are willing to enter the CPU, but they cannot, e.g. because they wait for disk activity.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "processes_total{unit=~\"$unit\"}",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "System active processes",
     "type": "timeseries",
     "description": "All system processes.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "processes_running{unit=~\"$unit\"}",
       "legendFormat": "running"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: interrupts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU interrupts",
     "type": "timeseries",
     "description": "Total number of CPU interrupts. Check the system interrupts graph that gives more detail about each interrupt and also the _CPUs_ section where interrupts are analyzed per CPU core.",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cpu_usage_irq{cpu=\"cpu-total\",unit=~\"$unit\"}",
       "legendFormat": "IRQ %"
      }
     ]
    },
    {
     "title": "System interrupts",
     "type": "timeseries",
     "description": "CPU interrupts in detail. At the _CPUs_ section, interrupts are analyzed per CPU core.",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cpu_usage_irq{cpu=\"cpu-total\",unit=~\"$unit\"}",
       "legendFormat": "IRQ %"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: softirqs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "System softirqs",
     "type": "timeseries",
     "description": "CPU softirqs in detail. At the _CPUs_ section, softirqs are analyzed per CPU core.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cpu_usage_softirq{cpu=\"cpu-total\",unit=~\"$unit\"}",
       "legendFormat": "softirq %"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: uptime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "System uptime",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "system_uptime{unit=~\"$unit\"}",
       "legendFormat": "uptime (s)"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "System swap",
     "type": "timeseries",
     "description": "System swap memory usage. Swap space is used when the amount of physical memory (RAM) is full. When the system needs more memory resources and the RAM is full, inactive pages in memory are moved to the swap space (usually a disk, a disk partition or a file).",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "mem_swap_used{unit=~\"$unit\"}/1048576",
       "legendFormat": "used"
      },
      {
       "expr": "mem_swap_free{unit=~\"$unit\"}/1048576",
       "legendFormat": "free"
      },
      {
       "expr": "mem_swap_cached{unit=~\"$unit\"}/1048576",
       "legendFormat": "cached"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory: system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Available RAM for applications",
     "type": "timeseries",
     "description": "Available Memory is estimated by the kernel, as the amount of RAM that can be used by userspace processes, without causing swapping.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "mem_available{unit=~\"$unit\"}/1048576",
       "legendFormat": "available"
      }
     ]
    },
    {
     "title": "Committed (allocated) memory",
     "type": "timeseries",
     "description": "Committed Memory, is the sum of all memory which has been allocated by processes.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "mem_committed_as{unit=~\"$unit\"}/1048576",
       "legendFormat": "committed"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory: kernel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Writeback memory",
     "type": "timeseries",
     "description": "**Dirty** is the amount of memory waiting to be written to disk. **Writeback** is how much memory is actively being written to disk.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "mem_write_back{unit=~\"$unit\"}/1048576",
       "legendFormat": "writeback"
      }
     ]
    },
    {
     "title": "Memory used by kernel",
     "type": "graph",
     "description": "The total amount of memory being used by the kernel. **Slab** is the amount of memory used by the kernel to cache data structures for its own use. **KernelStack** is the amount of memory allocated for each task done by the kernel. **PageTables** is the amount of memory decicated to the lowest level of page tables (A page table is used to turn a virtual address into a physical memory address). **VmallocUsed** is the amount of memory being used as virtual address space.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "(mem_slab{unit=~\"$unit\"} + mem_page_tables{unit=~\"$unit\"})/1048576",
       "legendFormat": "kernel (slab+pagetables)"
      }
     ]
    }
   ]
  },
  {
   "title": "Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "disk",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk I/O bandwidth",
     "type": "timeseries",
     "description": "Amount of data transferred to and from disk.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "rate(diskio_reads{unit=~\"$unit\"}[2m])",
       "legendFormat": "reads/s"
      },
      {
       "expr": "rate(diskio_writes{unit=~\"$unit\"}[2m])",
       "legendFormat": "writes/s"
      }
     ]
    },
    {
     "title": "Disk backlog",
     "type": "timeseries",
     "description": "Backlog is an indication of the duration of pending disk operations. On every I/O event the system is multiplying the time spent doing I/O since the last update of this field with the number of pending operations. While not accurate, this metric can provide an indication of the expected completion time of the operations in progress.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(diskio_io_time{unit=~\"$unit\"}[2m])",
       "legendFormat": "io_time ms/s"
      }
     ]
    },
    {
     "title": "Disk current I/O operations",
     "type": "timeseries",
     "description": "I/O operations currently in progress. This metric is a snapshot - it is not an average over the last interval.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "diskio_iops_in_progress{unit=~\"$unit\"}",
       "legendFormat": "iops in progress"
      }
     ]
    },
    {
     "title": "Average service time",
     "type": "timeseries",
     "description": "The average service time for completed I/O operations. This metric is calculated using the total busy time of the disk and the number of completed operations. If the disk is able to execute multiple parallel operations the reporting average service time will be misleading.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(diskio_merged_reads{unit=~\"$unit\"}[2m])",
       "legendFormat": "merged reads/s"
      },
      {
       "expr": "rate(diskio_merged_writes{unit=~\"$unit\"}[2m])",
       "legendFormat": "merged writes/s"
      }
     ]
    },
    {
     "title": "Disk utilization time",
     "type": "timeseries",
     "description": "Disk Utilization measures the amount of time the disk was busy with something. This is not related to its performance. 100% means that the system always had an outstanding operation on the disk.\n\nKeep in mind that depending on the underlying technology of the disk, 100% here may or may not be an indication of congestion.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "diskio_io_util{unit=~\"$unit\"}",
       "legendFormat": "utilization %"
      }
     ]
    },
    {
     "title": "Disk total I/O time",
     "type": "timeseries",
     "description": "The sum of the duration of all completed I/O operations. This number can exceed the interval if the disk is able to execute I/O operations in parallel.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "disk_used{unit=~\"$unit\"}/1073741824",
       "legendFormat": "used GiB"
      },
      {
       "expr": "disk_total{unit=~\"$unit\"}/1073741824",
       "legendFormat": "total GiB"
      }
     ]
    }
   ]
  },
  {
   "title": "Disks: filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "fs",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk space usage for filesystem",
     "type": "timeseries",
     "description": "Disk space utilization. reserved for root is automatically reserved by the system to prevent the root user from getting out of space.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "disk_inodes_used{unit=~\"$unit\"}",
       "legendFormat": "inodes used"
      }
     ]
    }
   ]
  },
  {
   "title": "VPN networking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "VPN interface: $vpninterface",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 29 },
     "repeat": "vpninterface",
     "targets": [
      {
       "expr": "rate(net_bytes_recv{unit=~\"$unit\",interface=~\"$vpninterface\"}[2m])*8/1000",
       "legendFormat": "recv"
      },
      {
       "expr": "rate(net_bytes_sent{unit=~\"$unit\",interface=~\"$vpninterface\"}[2m])*8/1000",
       "legendFormat": "sent"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv4 networking: sockets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "IPv4 raw sockets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "conntrack_ip_conntrack_count{unit=~\"$unit\"}",
       "legendFormat": "conntrack entries"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv4 networking: packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "IPv4 packets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_IpInReceives{unit=~\"$unit\",name=\"snmp\"}[2m])",
       "legendFormat": "in packets/s"
      },
      {
       "expr": "rate(nstat_IpOutRequests{unit=~\"$unit\",name=\"snmp\"}[2m])",
       "legendFormat": "out packets/s"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv4 networking: errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "IPv4 errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_IpInHdrErrors{unit=~\"$unit\",name=\"snmp\"}[2m]) + rate(nstat_IpInAddrErrors{unit=~\"$unit\",name=\"snmp\"}[2m]) + rate(nstat_IpInDiscards{unit=~\"$unit\",name=\"snmp\"}[2m])",
       "legendFormat": "in errors/s"
      },
      {
       "expr": "rate(nstat_IpOutDiscards{unit=~\"$unit\",name=\"snmp\"}[2m]) + rate(nstat_IpOutNoRoutes{unit=~\"$unit\",name=\"snmp\"}[2m])",
       "legendFormat": "out errors/s"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv4 networking: TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "IPv4 TCP sockets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nstat_TcpCurrEstab{unit=~\"$unit\",name=\"snmp\"}",
       "legendFormat": "established"
      },
      {
       "expr": "netstat_tcp_listen{unit=~\"$unit\"}",
       "legendFormat": "listening"
      },
      {
       "expr": "netstat_tcp_time_wait{unit=~\"$unit\"}",
       "legendFormat": "time_wait"
      }
     ]
    },
    {
     "title": "IPv4 TCP connections",
     "type": "timeseries",
     "description": "The number of established TCP connections (known as `CurrEstab`). This is a snapshot of the established connections at the time of measurement (i.e. a connection established and a connection disconnected within the same iteration will not affect this metric).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nstat_TcpCurrEstab{unit=~\"$unit\",name=\"snmp\"}",
       "legendFormat": "established"
      }
     ]
    },
    {
     "title": "IPv4 TCP opens",
     "type": "timeseries",
     "description": "**active** or `ActiveOpens` is the number of outgoing TCP **connections attempted** by this host. **passive** or `PassiveOpens` is the number of incoming TCP **connections accepted** by this host.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_TcpActiveOpens{unit=~\"$unit\",name=\"snmp\"}[2m])",
       "legendFormat": "active opens/s"
      },
      {
       "expr": "rate(nstat_TcpPassiveOpens{unit=~\"$unit\",name=\"snmp\"}[2m])",
       "legendFormat": "passive opens/s"
      }
     ]
    },
    {
     "title": "IPv4 TCP packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_TcpInSegs{unit=~\"$unit\",name=\"snmp\"}[2m])",
       "legendFormat": "in segs/s"
      },
      {
       "expr": "rate(nstat_TcpOutSegs{unit=~\"$unit\",name=\"snmp\"}[2m])",
       "legendFormat": "out segs/s"
      }
     ]
    },
    {
     "title": "IPv4 TCP errors",
     "type": "timeseries",
     "description": "`InErrs` is the number of TCP segments received in error (including header too small, checksum errors, sequence errors, bad packets - for both IPv4 and IPv6). `InCsumErrors` is the number of TCP segments received with checksum errors (for both IPv4 and IPv6). `RetransSegs` is the number of TCP segments retransmitted.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_TcpInErrs{unit=~\"$unit\",name=\"snmp\"}[2m])",
       "legendFormat": "in errs/s"
      },
      {
       "expr": "rate(nstat_TcpRetransSegs{unit=~\"$unit\",name=\"snmp\"}[2m])",
       "legendFormat": "retrans/s"
      }
     ]
    },
    {
     "title": "TCP connection aborts",
     "type": "timeseries",
     "description": "TCP connection aborts.\n\n**baddata** (`TCPAbortOnData`) happens while the connection is on `FIN_WAIT1` and the kernel receives a packet with a sequence number beyond the last one for this connection - the kernel responds with `RST` (closes the connection).\n\n**userclosed** (`TCPAbortOnClose`) happens when the kernel receives data on an already closed connection and responds with `RST`.\n\n**nomemory** (`TCPAbortOnMemory` happens when there are too many orphaned sockets (not attached to an fd) and the kernel has to drop a connection - sometimes it will send an `RST`, sometimes it won't.\n\n**timeout** (`TCPAbortOnTimeout`) happens when a connection times out.\n\n**linger** (`TCPAbortOnLinger`) happens when the kernel killed a socket that was already closed by the application and lingered around for long enough.\n\n**failed** (`TCPAbortFailed`) happens when the kernel attempted to send an `RST` but failed because there was no memory available.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_TcpExtTCPAbortOnData{unit=~\"$unit\",name=\"netstat\"}[2m])",
       "legendFormat": "on data/s"
      },
      {
       "expr": "rate(nstat_TcpExtTCPAbortOnTimeout{unit=~\"$unit\",name=\"netstat\"}[2m])",
       "legendFormat": "on timeout/s"
      }
     ]
    },
    {
     "title": "IPv4 TCP handshake issues",
     "type": "timeseries",
     "description": "`EstabResets` is the number of established connections resets (i.e. connections that made a direct transition from `ESTABLISHED` or `CLOSE_WAIT` to `CLOSED`).\n\n`OutRsts` is the number of TCP segments sent, with the `RST` flag set (for both IPv4 and IPv6).\n\n`AttemptFails` is the number of times TCP connections made a direct transition from either `SYN_SENT` or `SYN_RECV` to `CLOSED`, plus the number of times TCP connections made a direct transition from the `SYN_RECV` to `LISTEN`.\n\n`TCPSynRetrans` shows retries for new outbound TCP connections, which can indicate general connectivity issues or backlog on the remote host.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_TcpExtListenDrops{unit=~\"$unit\",name=\"netstat\"}[2m])",
       "legendFormat": "listen drops/s"
      },
      {
       "expr": "rate(nstat_TcpExtListenOverflows{unit=~\"$unit\",name=\"netstat\"}[2m])",
       "legendFormat": "overflows/s"
      }
     ]
    },
    {
     "title": "IPv4 TCP sockets memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "netstat_tcp_established{unit=~\"$unit\"} + netstat_tcp_close_wait{unit=~\"$unit\"} + netstat_tcp_time_wait{unit=~\"$unit\"}",
       "legendFormat": "tcp sockets"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv4 networking: UDP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "IPv4 UDP sockets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "netstat_udp_socket{unit=~\"$unit\"}",
       "legendFormat": "udp sockets"
      }
     ]
    },
    {
     "title": "IPv4 UDP packets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_UdpInDatagrams{unit=~\"$unit\",name=\"snmp\"}[2m])",
       "legendFormat": "in/s"
      },
      {
       "expr": "rate(nstat_UdpOutDatagrams{unit=~\"$unit\",name=\"snmp\"}[2m])",
       "legendFormat": "out/s"
      }
     ]
    },
    {
     "title": "IPv4 UDP sockets memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "netstat_udp_socket{unit=~\"$unit\"}",
       "legendFormat": "udp sockets"
      }
     ]
    },
    {
     "title": "IPv4 UDP errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_UdpInErrors{unit=~\"$unit\",name=\"snmp\"}[2m])",
       "legendFormat": "errors/s"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv4 networking: ICMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "IPv4 ICMP packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_IcmpInMsgs{unit=~\"$unit\",name=\"snmp\"}[2m])",
       "legendFormat": "in/s"
      },
      {
       "expr": "rate(nstat_IcmpOutMsgs{unit=~\"$unit\",name=\"snmp\"}[2m])",
       "legendFormat": "out/s"
      }
     ]
    },
    {
     "title": "IPv4 ICMP errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_IcmpInErrors{unit=~\"$unit\",name=\"snmp\"}[2m]) + rate(nstat_IcmpOutErrors{unit=~\"$unit\",name=\"snmp\"}[2m])",
       "legendFormat": "errors/s"
      }
     ]
    },
    {
     "title": "IPv4 ICMP messages",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_IcmpInEchos{unit=~\"$unit\",name=\"snmp\"}[2m])",
       "legendFormat": "echo req/s"
      },
      {
       "expr": "rate(nstat_IcmpInEchoReps{unit=~\"$unit\",name=\"snmp\"}[2m])",
       "legendFormat": "echo rep/s"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv4 networking: broadcast",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "IPv4 broadcast bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "targets": [
      {
       "expr": "rate(nstat_IpExtInBcastOctets{unit=~\"$unit\",name=\"netstat\"}[2m])*8/1000",
       "legendFormat": "in Kbits/s"
      },
      {
       "expr": "rate(nstat_IpExtOutBcastOctets{unit=~\"$unit\",name=\"netstat\"}[2m])*8/1000",
       "legendFormat": "out Kbits/s"
      }
     ]
    },
    {
     "title": "IPv4 broadcast packets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_IpExtInBcastPkts{unit=~\"$unit\",name=\"netstat\"}[2m])",
       "legendFormat": "in/s"
      },
      {
       "expr": "rate(nstat_IpExtOutBcastPkts{unit=~\"$unit\",name=\"netstat\"}[2m])",
       "legendFormat": "out/s"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv4 networking: ECN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "IPv4 ECN statistics",
     "type": "timeseries",
     "description": "[Explicit Congestion Notification (ECN)](https://en.wikipedia.org/wiki/Explicit_Congestion_Notification) is a TCP extension that allows end-to-end notification of network congestion without dropping packets.\n\nECN is an optional feature that may be used between two ECN-enabled endpoints when the underlying network infrastructure also supports it.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_IpExtInCEPkts{unit=~\"$unit\",name=\"netstat\"}[2m])",
       "legendFormat": "CE/s"
      },
      {
       "expr": "rate(nstat_IpExtInECT0Pkts{unit=~\"$unit\",name=\"netstat\"}[2m])",
       "legendFormat": "ECT0/s"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv6 networking: packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "IPv6 packets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_Ip6InReceives{unit=~\"$unit\",name=\"snmp6\"}[2m])",
       "legendFormat": "in/s"
      },
      {
       "expr": "rate(nstat_Ip6OutRequests{unit=~\"$unit\",name=\"snmp6\"}[2m])",
       "legendFormat": "out/s"
      }
     ]
    },
    {
     "title": "IPv6 ECT packets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_Ip6InECT0Pkts{unit=~\"$unit\",name=\"snmp6\"}[2m])",
       "legendFormat": "ECT0/s"
      },
      {
       "expr": "rate(nstat_Ip6InECT1Pkts{unit=~\"$unit\",name=\"snmp6\"}[2m])",
       "legendFormat": "ECT1/s"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv6 networking: tcp6",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "IPv6 TCP sockets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "netstat_tcp_established{unit=~\"$unit\"}",
       "legendFormat": "established"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv6 networking: udp6",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "IPv6 UDP sockets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "netstat_udp_socket{unit=~\"$unit\"}",
       "legendFormat": "udp sockets"
      }
     ]
    },
    {
     "title": "IPv6 UDP packets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_Udp6InDatagrams{unit=~\"$unit\",name=\"snmp6\"}[2m])",
       "legendFormat": "in/s"
      },
      {
       "expr": "rate(nstat_Udp6OutDatagrams{unit=~\"$unit\",name=\"snmp6\"}[2m])",
       "legendFormat": "out/s"
      }
     ]
    },
    {
     "title": "IPv6 UDP errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_Udp6InErrors{unit=~\"$unit\",name=\"snmp6\"}[2m])",
       "legendFormat": "errors/s"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv6 networking: multicast6",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "IPv6 multicast bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "targets": [
      {
       "expr": "rate(nstat_Ip6InMcastOctets{unit=~\"$unit\",name=\"snmp6\"}[2m])*8/1000",
       "legendFormat": "in Kbits/s"
      },
      {
       "expr": "rate(nstat_Ip6OutMcastOctets{unit=~\"$unit\",name=\"snmp6\"}[2m])*8/1000",
       "legendFormat": "out Kbits/s"
      }
     ]
    },
    {
     "title": "IPv6 multicast packets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_Ip6InMcastPkts{unit=~\"$unit\",name=\"snmp6\"}[2m])",
       "legendFormat": "in/s"
      },
      {
       "expr": "rate(nstat_Ip6OutMcastPkts{unit=~\"$unit\",name=\"snmp6\"}[2m])",
       "legendFormat": "out/s"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv6 networking: icmp6",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "IPv6 ICMP messages",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_Icmp6InMsgs{unit=~\"$unit\",name=\"snmp6\"}[2m])",
       "legendFormat": "in/s"
      },
      {
       "expr": "rate(nstat_Icmp6OutMsgs{unit=~\"$unit\",name=\"snmp6\"}[2m])",
       "legendFormat": "out/s"
      }
     ]
    },
    {
     "title": "IPv6 ICMP errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_Icmp6InErrors{unit=~\"$unit\",name=\"snmp6\"}[2m])",
       "legendFormat": "in errors/s"
      },
      {
       "expr": "rate(nstat_Icmp6OutErrors{unit=~\"$unit\",name=\"snmp6\"}[2m])",
       "legendFormat": "out errors/s"
      }
     ]
    },
    {
     "title": "IPv6 ICMP echo",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_Icmp6InEchos{unit=~\"$unit\",name=\"snmp6\"}[2m])",
       "legendFormat": "in/s"
      },
      {
       "expr": "rate(nstat_Icmp6OutEchoReplies{unit=~\"$unit\",name=\"snmp6\"}[2m])",
       "legendFormat": "out/s"
      }
     ]
    },
    {
     "title": "IPv6 router messages",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_Icmp6InRouterAdvertisements{unit=~\"$unit\",name=\"snmp6\"}[2m])",
       "legendFormat": "advert/s"
      },
      {
       "expr": "rate(nstat_Icmp6OutRouterSolicits{unit=~\"$unit\",name=\"snmp6\"}[2m])",
       "legendFormat": "solicits/s"
      }
     ]
    },
    {
     "title": "IPv6 neighbor messages",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_Icmp6InNeighborSolicits{unit=~\"$unit\",name=\"snmp6\"}[2m])",
       "legendFormat": "solicits/s"
      },
      {
       "expr": "rate(nstat_Icmp6OutNeighborAdvertisements{unit=~\"$unit\",name=\"snmp6\"}[2m])",
       "legendFormat": "advert/s"
      }
     ]
    },
    {
     "title": "IPv6 ICMP MLDv2 reports",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_Icmp6InMLDv2Reports{unit=~\"$unit\",name=\"snmp6\"}[2m])",
       "legendFormat": "reports/s"
      }
     ]
    },
    {
     "title": "IPv6 ICMP types",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nstat_Icmp6InMsgs{unit=~\"$unit\",name=\"snmp6\"}[2m])",
       "legendFormat": "in/s"
      },
      {
       "expr": "rate(nstat_Icmp6OutMsgs{unit=~\"$unit\",name=\"snmp6\"}[2m])",
       "legendFormat": "out/s"
      }
     ]
    }
   ]
  }
 ]
}