{
 "title": "Network traffic by remote host",
 "tags": [
  "monitoring",
  "timescale",
  "unit"
 ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "uuid",
    "label": "Unit",
    "query": "SELECT uuid AS __value, name  AS __text FROM units"
   },
   { "name": "host", "query": "%" },
   { "name": "DS_TIMESCALE", "label": "Local Timescale", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Total traffic",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT bytes FROM ca_dpi_stats_hourly_host\nWHERE $__timeFilter(bucket) AND uuid = '$uuid' AND host like '$host'"
    }
   ]
  },
  {
   "title": "Traffic by hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT bucket, sum(bytes) as bytes FROM ca_dpi_stats_hourly_host\nWHERE $__timeFilter(bucket) AND uuid = '$uuid' AND host like '$host'\nGROUP BY bucket\nORDER BY bucket"
    }
   ]
  },
  {
   "title": "Traffic by hour per client",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('30m', time) AS time,\n  client_address as client,\n  SUM(bytes) AS value\nFROM dpi_stats\nWHERE $__timeFilter(time) AND host LIKE '$host' AND uuid = '$uuid'\nGROUP BY time, client\nORDER BY time"
    }
   ]
  },
  {
   "title": "Total traffic by client",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT client_address, client_name, SUM(bytes) as bytes FROM dpi_stats \nWHERE $__timeFilter(time) AND uuid = '$uuid' AND host LIKE '$host'\nGROUP BY client_address, client_name\nORDER BY bytes DESC"
    }
   ]
  }
 ]
}