{
 "title": "Network traffic",
 "tags": [
  "unit",
  "timescale",
  "monitoring"
 ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "uuid",
    "label": "Unit",
    "query": "SELECT uuid AS __value, name AS __text FROM units ORDER BY created_at DESC"
   },
   { "name": "DS_TIMESCALE", "label": "Local Timescale", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Total traffic",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(bytes) FROM ca_dpi_stats_hourly_bytes\nWHERE $__timeFilter(bucket) AND uuid = '$uuid'"
    }
   ]
  },
  {
   "title": "Traffic by hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT bucket, bytes FROM ca_dpi_stats_hourly_bytes \nWHERE $__timeFilter(bucket) AND uuid = '$uuid'\nGROUP BY bucket, bytes"
    }
   ]
  },
  {
   "title": "Top 10 applications",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE\n        WHEN application_rank <= 10 THEN application\n        ELSE 'Other'\n    END AS application,\n    SUM(bytes) AS total_bytes\nFROM (\n    SELECT\n        replace(application, 'netify.', '') AS application,\n        SUM(bytes) AS bytes,\n        ROW_NUMBER() OVER (ORDER BY SUM(bytes) DESC) AS application_rank\n    FROM\n        ca_dpi_stats_hourly_application\n    WHERE\n        $__timeFilter(bucket) AND uuid = '$uuid'\n    GROUP BY\n        application\n) AS ranked_applications\nGROUP BY\n    CASE\n        WHEN application_rank <= 10 THEN application\n        ELSE 'Other'\n    END\nORDER BY\n    total_bytes DESC;\n"
    }
   ]
  },
  {
   "title": "Top 10 clients",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT client_name, sum(bytes) FROM ca_dpi_stats_hourly_client\nWHERE $__timeFilter(bucket) AND uuid = '$uuid'\nGROUP BY client_name"
    }
   ]
  },
  {
   "title": "Top 10 protocols",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE\n        WHEN protocol_rank <= 10 THEN protocol\n        ELSE 'Other'\n    END AS protocol,\n    SUM(bytes) AS total_bytes\nFROM (\n    SELECT\n        protocol,\n        SUM(bytes) AS bytes,\n        ROW_NUMBER() OVER (ORDER BY SUM(bytes) DESC) AS protocol_rank\n    FROM\n        ca_dpi_stats_hourly_protocol\n    WHERE\n        $__timeFilter(bucket) AND uuid = '$uuid'\n    GROUP BY\n        protocol\n) AS ranked_protocols\nGROUP BY\n    CASE\n        WHEN protocol_rank <= 10 THEN protocol\n        ELSE 'Other'\n    END\nORDER BY\n    total_bytes DESC;\n"
    }
   ]
  },
  {
   "title": "Top 10 remote hosts",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE\n        WHEN host_rank <= 10 THEN host\n        ELSE 'Other'\n    END AS host,\n    SUM(bytes) AS total_bytes\nFROM (\n    SELECT\n        host,\n        SUM(bytes) AS bytes,\n        ROW_NUMBER() OVER (ORDER BY SUM(bytes) DESC) AS host_rank\n    FROM\n        ca_dpi_stats_hourly_host\n    WHERE\n        $__timeFilter(bucket) AND uuid = '$uuid'\n    GROUP BY\n        host\n) AS ranked_hosts\nGROUP BY\n    CASE\n        WHEN host_rank <= 10 THEN host\n        ELSE 'Other'\n    END\nORDER BY\n    total_bytes DESC;\n"
    }
   ]
  },
  {
   "title": "Protocols",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT protocol, sum(bytes) as bytes FROM ca_dpi_stats_hourly_protocol\nWHERE $__timeFilter(bucket) AND  uuid = '$uuid'\nGROUP BY protocol\nORDER BY bytes DESC"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT replace(application, 'netify.', '') AS application, sum(bytes) as bytes FROM ca_dpi_stats_hourly_application\nWHERE $__timeFilter(bucket) AND  uuid = '$uuid'\nGROUP BY application\nORDER BY bytes DESC"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT client_address, client_name, bytes FROM ca_dpi_stats_hourly_client\nWHERE $__timeFilter(bucket) AND uuid = '$uuid'\nORDER BY bytes DESC\n"
    }
   ]
  },
  {
   "title": "Remote hosts",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT host, sum(bytes) as bytes FROM ca_dpi_stats_hourly_host\nWHERE $__timeFilter(bucket) AND uuid = '$uuid'\nGROUP BY host\nORDER BY bytes DESC"
    }
   ]
  }
 ]
}