{
 "title": "VPN",
 "tags": [
  "timescale",
  "unit",
  "monitoring"
 ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_TIMESCALE", "label": "Local Timescale", "query": "grafana-postgresql-datasource" },
   {
    "name": "uuid",
    "label": "Unit",
    "query": "SELECT uuid AS __value, name AS __text FROM units ORDER BY created_at DESC"
   },
   {
    "name": "rwinstance",
    "label": "Road Warrior server",
    "query": "SELECT instance AS __value, CONCAT(name,' (',instance,')') AS __text FROM openvpn_config WHERE uuid = '$uuid' AND type = 'rw'"
   },
   { "name": "DS_PROMETHEUS", "label": "Local Prometheus", "query": "prometheus" },
   {
    "name": "user",
    "label": "User",
    "query": "SELECT common_name as __value FROM ovpnrw_connections WHERE uuid = '$uuid'"
   },
   {
    "name": "rwinterface",
    "query": "SELECT device AS __value FROM openvpn_config WHERE uuid = '$uuid' AND instance LIKE '$rwinstance'"
   },
   {
    "name": "tunnel",
    "label": "Tunnels",
    "query": "SELECT instance AS __value, CONCAT(name,' (',instance,')') AS __text FROM openvpn_config WHERE uuid = '$uuid' AND type  IN ('server', 'client')"
   },
   {
    "name": "tuninterface",
    "query": "SELECT device AS __value FROM openvpn_config WHERE uuid = '$uuid' AND instance = '$tunnel'"
   }
  ]
 },
 "panels": [
  {
   "title": "OpenVPN Road Warrior instance: $rwinstance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance"
  },
  {
   "title": "Number of connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM ovpnrw_connections\nWHERE $__timeFilter(time) AND uuid = '$uuid' AND instance LIKE '$rwinstance'"
    }
   ]
  },
  {
   "title": "Connections by time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT time, count(*) FROM ovpnrw_connections\nWHERE $__timeFilter(time) AND uuid = '$uuid' AND instance LIKE '$rwinstance'\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Total traffic",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(bytes_sent) + SUM(bytes_received) as bytes FROM ca_ovpnrw_connections_hourly_bytes\nWHERE $__timeFilter(bucket) AND uuid = '$uuid' AND instance LIKE '$rwinstance'\n"
    }
   ]
  },
  {
   "title": "Top 20 user by traffic",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(bytes_sent) + SUM(bytes_received) as bytes, common_name as user FROM ca_ovpnrw_connections_hourly_bytes\nWHERE $__timeFilter(bucket) AND uuid = '$uuid' AND instance LIKE '$rwinstance'\nGROUP BY common_name\nORDER by bytes DESC\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Interface $rwinterface traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "rate(net_bytes_recv{unit=~'$uuid',interface=~'$rwinterface'}[2m])*8/1000",
     "legendFormat": "received"
    },
    {
     "expr": "rate(net_bytes_sent{unit=~'$uuid',interface=~'$rwinterface'}[2m])*8/1000",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Public IP connections",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS count, country AS lookup FROM ovpnrw_connections\nWHERE $__timeFilter(time) AND uuid = '$uuid' AND instance LIKE '$rwinstance'\nGROUP BY lookup"
    }
   ]
  },
  {
   "title": "Traffic by hour",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT bucket, SUM(bytes_sent) + SUM(bytes_received) as bytes FROM ca_ovpnrw_connections_hourly_bytes\nWHERE $__timeFilter(bucket) AND uuid = '$uuid' AND instance LIKE '$rwinstance'\nGROUP BY bucket\nORDER BY bucket \n"
    }
   ]
  },
  {
   "title": "Traffic by user: $user",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "repeat": "user",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT bucket, SUM(bytes_sent) + SUM(bytes_received) as bytes FROM ca_ovpnrw_connections_hourly_bytes\nWHERE $__timeFilter(bucket) AND uuid = '$uuid' AND instance LIKE '$rwinstance' AND common_name like '$user'\n  AND (bytes_sent + bytes_received) > 0\nGROUP BY bucket\nORDER BY bucket"
    }
   ]
  },
  {
   "title": "Connection details: $rwinstance",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT common_name, TO_TIMESTAMP(start_time) AS start_time, duration, TO_TIMESTAMP(start_time + duration) AS end_time, bytes_received, bytes_sent, virtual_ip_addr, remote_ip_addr\nFROM ovpnrw_connections\nWHERE uuid = '$uuid' AND instance LIKE '$rwinstance' AND $__timeFilter(time) "
    }
   ]
  },
  { "title": "OpenVPN tunnels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Interface $tuninterface traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "rate(net_bytes_recv{unit=~'$uuid',interface=~'$tuninterface'}[2m])*8/1000",
     "legendFormat": "received"
    },
    {
     "expr": "rate(net_bytes_sent{unit=~'$uuid',interface=~'$tuninterface'}[2m])*8/1000",
     "legendFormat": "sent"
    }
   ]
  }
 ]
}