#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2 # Send any output to stderr, to not alter the action response protocol
set -e

start=$(echo $TCP_PORTS_RANGE | cut -d'-' -f1)

ovpn_udp_port=$start
api_port=$(($start+1))
ui_port=$(($start+2))
proxy_port=$(($start+3))
promtail_port=$(($start+4))
# port 6 and 7 are reserved for loki
# port 8 is reserved for prometheus
# port 9 is reserved for grafana

num=$(echo $MODULE_ID | sed 's/nethsecurity\-controller//')

secret=$(uuidgen | sha256sum | awk '{print $1}')

cat << EOF > network.env
OVPN_UDP_PORT=$ovpn_udp_port
OVPN_TUN=tunnsc$num
API_PORT=$api_port
API_BIND_IP=127.0.0.1
LISTEN_ADDRESS=127.0.0.1:$api_port
UI_PORT=$ui_port
UI_BIND_IP=127.0.0.1
PROXY_PORT=$proxy_port
PROXY_BIND_UI=127.0.0.1
EOF

cat << EOF > secret.env
SECRET_JWT=$secret
EOF

mkdir -p clients
