#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import agent

ovpn_port = os.environ['TCP_PORTS_RANGE'].split('-')[0]
agent.assert_exp(agent.add_public_service(os.environ['MODULE_ID'], [f"{ovpn_port}/udp"]))
