#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json
import ipaddress
import subprocess
import agent
import agent.tasks

request = json.load(sys.stdin)

def validation_failed(field, value, error):
    agent.set_status('validation-failed')
    json.dump([{'field': field, 'parameter': field, 'value': value, 'error': error}], fp=sys.stdout)
    sys.exit(2)

ovpn_network = request['ovpn_network']
ovpn_netmask = request['ovpn_netmask']

try:
    vpn_network = ipaddress.IPv4Network(f'{ovpn_network}/{ovpn_netmask}')
except ipaddress.NetmaskValueError:
    validation_failed('ovpn_netmask', ovpn_netmask, 'invalid_netmask')
except ValueError:
    validation_failed('ovpn_network', ovpn_network, 'invalid_network')
if not 20 <= vpn_network.prefixlen <= 24:
    validation_failed('ovpn_netmask', ovpn_netmask, 'netmask_out_of_range')

subprocess.run(['systemctl', '--user', 'stop', 'controller.service'], check=True)

network = agent.read_envfile('network.env')
agent.assert_exp(agent.remove_tun(network.get('OVPN_TUN')))

with open('config.json', 'r') as cf:
    config = json.load(cf)
config['ovpn_network'] = ovpn_network
config['ovpn_netmask'] = ovpn_netmask
with open('config.json', 'w') as cf:
    json.dump(config, cf)

# Keep the current Let's Encrypt setting of the route
config.pop('lets_encrypt', None)
response = agent.tasks.run(agent_id=os.environ['AGENT_ID'], action='configure-module', data=config)
agent.assert_exp(response['exit_code'] == 0)
