#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-2.0-only
#

import json
import subprocess
import sys
import agent

db = agent.read_envfile('db.env')

def count(table):
    p = subprocess.run(["/usr/bin/podman", "exec", "timescale", "psql", "-U", db["POSTGRES_USER"], "-p", db["POSTGRES_PORT"], "-tAc", f"SELECT count(*) FROM {table}"], capture_output=True, text=True, check=True)
    return int(p.stdout.strip())

units = 0
users = 0
try:
    units = count("units")
except Exception as ex:
    print(agent.SD_ERR, ex, file=sys.stderr)

try:
    users = count("accounts")
except Exception as ex:
    print(agent.SD_ERR, ex, file=sys.stderr)

json.dump({
    "units": units,
    "active_users": users,
    "total_users": users
}, fp=sys.stdout)
