{
 "title": "Connectivity",
 "tags": [
  "timescale",
  "unit",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_TIMESCALE", "label": "Local Timescale", "query": "grafana-postgresql-datasource" },
   {
    "name": "uuid",
    "label": "Unit",
    "query": "SELECT uuid AS __value, name AS __text FROM units"
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "wan",
    "label": "WAN interface",
    "query": "SELECT device AS __value, interface AS __text FROM wan_config WHERE uuid = '$uuid'"
   }
  ]
 },
 "panels": [
  {
   "title": "MultiWAN status",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    interface,\n    device,\n    status,\n    created_at AS last_update_time\nFROM wan_config\nWHERE uuid = '$uuid'\nORDER BY interface\n"
    }
   ]
  },
  {
   "title": "Last 3 downtime events",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    time,\n    wan,\n    interface\nFROM mwan_events\nWHERE event = 'offline' AND uuid = '$uuid'\nORDER BY time DESC\nLIMIT 3;"
    }
   ]
  },
  {
   "title": "MultiWAN events by time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT bucket, count(*) as count FROM ca_mwan_events_hourly\nWHERE $__timeFilter(bucket) AND uuid = '$uuid'\nGROUP by bucket"
    }
   ]
  },
  {
   "title": "Interface $wan traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "repeat": "wan",
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "netdata_net_net_kilobits_persec_average{unit=~'$uuid',chart='net.$wan'}",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 23 },
   "options": {
    "content": "# Line quality\n\nPing sent to configured hosts, the traffic\nmay use any interface."
   }
  },
  {
   "title": "Ping latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "netdata_fping_latency_ms_average{unit=~'$uuid'}",
     "legendFormat": "{{dimension}}-{{family}}"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "netdata_fping_packets_packets_average{unit=~'$uuid'}",
     "legendFormat": "{{dimension}}-{{family}}"
    }
   ]
  },
  {
   "title": "Quality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "netdata_fping_quality_percentage_average{unit=~'$uuid'}",
     "legendFormat": "{{dimension}}-{{family}}"
    }
   ]
  }
 ]
}