{
 "title": "Network traffic by client",
 "tags": [
  "monitoring",
  "unit",
  "timescale"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "uuid",
    "label": "Unit",
    "query": "SELECT uuid AS __value, name AS __text FROM units"
   },
   { "name": "client_address", "query": "%" },
   { "name": "DS_TIMESCALE", "label": "Local Timescale", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Hostname",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT client_name \nFROM ca_dpi_stats_hourly_client\nWHERE $__timeFilter(bucket) AND uuid = '$uuid' AND client_address = '$client_address'"
    }
   ]
  },
  {
   "title": "Traffic by hour",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT bucket, bytes \nFROM ca_dpi_stats_hourly_client\nWHERE $__timeFilter(bucket) AND uuid = '$uuid' AND client_address = '$client_address'"
    }
   ]
  },
  {
   "title": "Total traffic",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT bytes \nFROM ca_dpi_stats_hourly_client\nWHERE $__timeFilter(bucket) AND uuid = '$uuid' AND client_address = '$client_address'"
    }
   ]
  },
  {
   "title": "Top 10 applications",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT REPLACE(application, 'netify.', '') as application, SUM(bytes) AS BYTES FROM dpi_stats \nWHERE application!='' AND $__timeFilter(time) AND client_address like '$client_address' AND uuid = '$uuid'\nGROUP BY application\nORDER BY bytes desc\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top 10 protocols",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT protocol, SUM(bytes) FROM dpi_stats \nWHERE protocol!='' AND $__timeFilter(time) AND client_address like '$client_address' AND uuid = '$uuid'\nGROUP BY protocol"
    }
   ]
  },
  {
   "title": "Top 10 remote hosts",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT host, SUM(bytes) as bytes FROM dpi_stats \nWHERE host!='' AND $__timeFilter(time) AND uuid = '$uuid' AND client_address like '$client_address'\nGROUP BY host\nORDER BY bytes DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Traffic by application",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT REPLACE(application, 'netify.', '') as application, SUM(bytes) as bytes FROM dpi_stats \nWHERE application!='' AND $__timeFilter(time) AND client_address like '$client_address' AND uuid = '$uuid'\nGROUP BY application\nORDER BY bytes DESC"
    }
   ]
  },
  {
   "title": "Traffic by protocol",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT protocol, SUM(bytes) as bytes FROM dpi_stats \nWHERE protocol!='' AND $__timeFilter(time) AND client_address like '$client_address' AND uuid = '$uuid'\nGROUP BY protocol\nORDER BY bytes DESC"
    }
   ]
  },
  {
   "title": "Traffic by host",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT host, SUM(bytes) as bytes FROM dpi_stats \nWHERE host!='' AND $__timeFilter(time) AND uuid = '$uuid' AND client_address like '$client_address'\nGROUP BY host\nORDER BY bytes DESC"
    }
   ]
  }
 ]
}