{
 "title": "Security",
 "tags": [
  "monitoring",
  "unit",
  "timescale"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "uuid",
    "label": "Unit",
    "query": "SELECT uuid AS __value, name AS __text FROM units"
   },
   { "name": "DS_TIMESCALE", "label": "Local Timescale", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Threats\n\nBlocked IPs based on loaded blocklist categories."
   }
  },
  {
   "title": "Blocked threats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM ca_ts_malware_hourly_direction\nWHERE $__timeFilter(bucket) AND uuid = '$uuid'"
    }
   ]
  },
  {
   "title": "Top 10 blocked threats by IPs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT src, count(*) AS count FROM ca_ts_malware_hourly_direction\nWHERE $__timeFilter(bucket) AND uuid = '$uuid'\nGROUP by src\nORDER by count DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Blocked threats by chain",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT chain, SUM(count) FROM ca_ts_malware_hourly_chain\nWHERE $__timeFilter(bucket) AND uuid = '$uuid'\nGROUP by chain"
    }
   ]
  },
  {
   "title": "Blocked threats by category",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT category, SUM(count) FROM ca_ts_malware_hourly_category\nWHERE $__timeFilter(bucket) AND uuid = '$uuid'\nGROUP by category"
    }
   ]
  },
  {
   "title": "Blocked threats",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT count(*) as count, country AS lookup FROM ca_ts_malware_hourly_country\nWHERE $__timeFilter(bucket) AND uuid = '$uuid'\nGROUP BY country"
    }
   ]
  },
  {
   "title": "Blocked threats by time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT bucket, count(*) FROM ca_ts_malware_hourly_direction\nWHERE $__timeFilter(bucket) AND uuid = '$uuid'\nGROUP by bucket"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 24 },
   "options": {
    "content": "# Attacks\n\nBlocked IPs based on brute force attacks."
   }
  },
  {
   "title": "Blocked attacks",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(count) FROM ca_ts_attacks_hourly \nWHERE $__timeFilter(bucket) AND uuid = '$uuid'"
    }
   ]
  },
  {
   "title": "Top 10 blocked attack by country",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 9, "x": 5, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT country, count(*) as count FROM ts_attacks \nWHERE $__timeFilter(time) AND uuid = '$uuid'\nGROUP by country\nORDER by count DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top 10 blocked attacks by IP",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT ip, count(*) as count FROM ts_attacks\nWHERE $__timeFilter(time) AND uuid = '$uuid'\nGROUP BY ip\nORDER BY count DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Blocked attacks",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT count(*) as count, country AS lookup FROM ca_ts_attacks_hourly \nWHERE $__timeFilter(bucket) AND uuid = '$uuid'\nGROUP BY country"
    }
   ]
  },
  {
   "title": "Blocked attacks by hour",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT bucket, count(*) FROM ca_ts_attacks_hourly\nWHERE $__timeFilter(bucket) AND uuid = '$uuid'\nGROUP by bucket"
    }
   ]
  },
  {
   "title": "Blocked by countries",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT country, count(*) FROM ca_ts_malware_hourly_country\nWHERE $__timeFilter(bucket) AND uuid = '$uuid'\nGROUP BY country\nORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Blocked by IP",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT ip, count(*) as count FROM ts_attacks\nWHERE $__timeFilter(time) AND uuid = '$uuid'\nGROUP BY ip\nORDER BY count DESC\nLIMIT 20"
    }
   ]
  }
 ]
}