#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

if [ -f secret.env ] && ! grep -q "^PROMETHEUS_AUTH_USERNAME=" "$secrets_env"; then
    prometheus_user=prometheus_$RANDOM
    prometheus_secret=$(uuidgen | sha256sum | awk '{print $1}')
    echo "PROMETHEUS_AUTH_USERNAME=$prometheus_user" >> secret.env
    echo "PROMETHEUS_AUTH_PASSWORD=$prometheus_secret" >> secret.env
fi
