#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# Set PUBLIC_ENDPOINTS if not already set

import agent

network = agent.read_envfile('network.env')
if 'PUBLIC_ENDPOINTS' not in network:
    network['PUBLIC_ENDPOINTS'] = '/api/units/register'
    agent.write_envfile('network.env', network)
