#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import agent
network = agent.read_envfile('network.env')
agent.assert_exp(agent.remove_public_service(os.environ['MODULE_ID']))
agent.assert_exp(agent.remove_custom_zone(network.get('OVPN_TUN')))
