#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import json
import sys
import agent
import random
import string
import os.path


if os.path.isfile('config.json'):
    # Read current configuration from config file
    with open('config.json', 'r') as cf:
        config = json.loads(cf.read())

    # Cleanup password hash to avoid changes from the UI
    config['api_password'] = ''
else:
    # Prepare random values for first-configuration
    # Pick a newtork inside 172.16.0.0/12 (range 172.16.0.0-172.31.255.255)
    foctet=random.randrange(16,31)
    soctet=random.randrange(1,254)

    config = {'host': '', 'lets_encrypt': False, 'ovpn_network': f'172.{foctet}.{soctet}.0', 'ovpn_netmask': '255.255.255.0', 'ovpn_cn': 'nextsec', 'api_user': 'admin', 'api_password': ''}

    characters = list(string.ascii_letters + string.digits + "!@#$%^&*()")
    random.shuffle(characters)
    password = []
    for i in range(10):
        password.append(random.choice(characters))
    random.shuffle(password)
    config["api_password"] = ''.join(password)

json.dump(config, fp=sys.stdout)
