#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json
import agent.tasks

config = {}

# Read current configuration from config file
with open('config.json', 'r') as cf:
    config = json.loads(cf.read())

agent.tasks.run(agent_id=os.environ['AGENT_ID'], action='configure-module', data=config)
