#!/bin/sh

# Load database credentials
. ./db.env

# Wait for database to be ready pooling every 5 seconds
until podman exec timescale pg_isready -U "${POSTGRES_USER}" -p "${POSTGRES_PORT}" -d "${POSTGRES_DB}"; do
  sleep 5
done

# Load dump avoiding issues on timescaledb hypertables
podman exec timescale psql -U "${POSTGRES_USER}" -p "${POSTGRES_PORT}" -d "${POSTGRES_DB}" -c "CREATE EXTENSION IF NOT EXISTS timescaledb; SELECT timescaledb_pre_restore();"
podman exec timescale psql -U "${POSTGRES_USER}" -p "${POSTGRES_PORT}" < backup.sql
podman exec timescale psql -U "${POSTGRES_USER}" -p "${POSTGRES_PORT}" -d "${POSTGRES_DB}" -c "SELECT timescaledb_post_restore();"
